SELECT TOP (1000) [fullname]
      ,[Place]
      ,[Time]
      ,[Total_Minutes]
      ,[City]
      ,[State]
      ,[Age]
      ,[Gender]
      ,[latlong]
  FROM [projects].[dbo].[vw_ultra]
